version: '3.7'

services:

  wordpress:
    build: .
    image: ${podName}-wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${podName}.rule=Host(`${hostRule}`)
      - traefik.http.routers.${podName}.entrypoints=websecure
      - traefik.http.services.${podName}.loadbalancer.server.port=80
      - traefik.docker.network=${podName}_frontend
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${dbUser}
      WORDPRESS_DB_PASSWORD: ${dbPass}
      WORDPRESS_DB_NAME: ${dbName}
    volumes:
      - ./content:/var/www/html/wp-content
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.${podName}.rule=Host(`${hostRule}`)
        - traefik.http.routers.${podName}.entrypoints=websecure
        - traefik.http.services.${podName}.loadbalancer.server.port=80
        - traefik.docker.network=${podName}_frontend

  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${dbName}
      MYSQL_USER: ${dbUser}
      MYSQL_PASSWORD: ${dbPass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  backup:
    image: zeenlym/mariadb-backup
    depends_on:
      - mariadb
    restart: always
    networks:
      - backend
    environment:
      - TIMEZONE=${timeZone}
      - SCHEDULE=0 0 3 * *
      - BACKUP_METHOD=mysqldump
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPass}
    volumes:
      - ./backup:/backup
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

networks:
  frontend:
  backend:
